---
title: "Analisis de desbosque por actividad Minera"
author: "Gorky Florez Castillo"
date: "25/11/2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: [ "twitter", "facebook", "whatsapp", "instagram", "telegram", "linkedin", "pinterest" ]
    source_code: "https://github.com/GorkyFlorez"
    theme: yeti
---

```{r setup, include=FALSE}

library(sf)
library(spData)
library(ggplot2)
library(cowplot)
library(rcartocolor)
library(raster)
library(RStoolbox)
library(landsat8)
library(ggspatial)
library(leaflet)
library(leaflet.extras)
library(leaflet.extras2)
library(leaflet.providers)
library(leafem)
Sent_2016      <- raster("Raster/2016_AV.tif")
Sent_2021      <- raster("Raster/2021.tif")
Concesion      <- st_read("SHP/Concesion.shp")
Concesio       <- st_transform(Concesion ,crs = st_crs("+proj=longlat +datum=WGS84 +no_defs"))
Vertice        <- st_read("SHP/Vertices.shp")
Vertices       <- st_transform(Vertice ,crs = st_crs("+proj=longlat +datum=WGS84 +no_defs"))
Area_desbosc   <- st_read("SHP/Area_desboscada.shp")
Area_desbosb   <- st_transform(Area_desbosc ,crs = st_crs("+proj=longlat +datum=WGS84 +no_defs"))

pal =c("#47A612ff", "#8BC60Aff", "#47A612ff", "#8BC60Aff","#83D216ff", "#8BEE1Dff", "#F1FF32ff", "#EACF87ff", "#FFB1FFff", "#FF98C6ff", "#DA62C3ff", "#4F3667ff")

# raster_colorPal_elev <- colorNumeric(palette = terrain.colors(3000),domain = values(band4$X2016_AV),na.color = NA) # Define palette
#Definiendo el Logo
m="https://images.vexels.com/media/users/3/143561/isolated/preview/afa3aa927b63061e3b0222b7dab9cdbf-ubicaci--n-n--utica-norte-flecha-vintage-by-vexels.png"
polygon_popup <- paste0("<strong>Contrato: </strong>", Concesio$contra, "<br>",          # Label
                        "<strong>Titular: </strong>", Concesio$nomtit,"<br>",
                        "<strong>Otorgado: </strong>", Concesio$nomrel,"<br>",
                        "<strong>Sector: </strong>", Concesio$sector,"<br>",
                        "<strong>Perimetro: </strong>", Concesio$perime,"<br>",
                        "<strong>Area SIG: </strong>", Concesio$supsig,"<br>")

polygon_popup3 <- paste0("<strong>Area deboscada: </strong>", Area_desbosb$Area , "<br>")

polygon_popup4 <- paste0("<strong>Punto: </strong>", Vertices$Id_Mapa , "<br>")


Mapa_2016= leaflet() %>%
  addControl(html = "<p><strong><em>Analisis de Desbosque- 2016</em></strong></p>",
             position = "topright")%>%
  addLogo(m,url = "https://images.vexels.com/media/users/3/143561/isolated/preview/afa3aa927b63061e3b0222b7dab9cdbf-ubicaci--n-n--utica-norte-flecha-vintage-by-vexels.png",
          position = "topleft",
          offset.x = 50,
          offset.y = 10,
          width = 100,
          height = 100)%>%
  addPolygons(data = Concesio, opacity = 0.6, group ="Concesion MARIZABETH",popup = polygon_popup) %>%
  addPolygons(data = Area_desbosb, opacity = 0.1, group ="Area Desboscada", color = "red" ,popup = polygon_popup3) %>%
  addCircles(data = Vertices ,popup = polygon_popup4,
             color = "red",
             radius =8,
             weight = 1,
             opacity = 1,
             fill = T,
             fillColor = "blue",
             fillOpacity = 1,
             group = "Vertices")%>%
  addRasterImage(Sent_2016 , project = TRUE,colors = pal, group = "Imagen Sentinel 2")%>%
  addLayersControl(baseGroups = c("Satellite", "OSM","OTM","Toner","Terrain","Terrain.ESRI", "Toner Lite","CartoDB.Positron", "relieve"),
                 overlayGroups = c("Imagen Sentinel 2", "Concesion MARIZABETH", "Vertices", "Area Desboscada"),
                 position = "topright",
                 options = layersControlOptions(collapsed = T))%>%
  addProviderTiles(providers$OpenStreetMap, group = "OSM")%>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite")%>%
  addProviderTiles(providers$OpenTopoMap, group = "OTM")%>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  addProviderTiles(providers$Esri.WorldStreetMap, group = "Terrain.ESRI") %>%
  addProviderTiles(providers$CartoDB.Positron, group ="CartoDB.Positron") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addMiniMap(tiles = providers$Esri.WorldImagery,toggleDisplay = TRUE)%>%
  addScaleBar(position = "bottomright",options = scaleBarOptions(maxWidth = 100,
                                                                 metric = TRUE,
                                                                 imperial = TRUE,
                                                                 updateWhenIdle = TRUE)) %>%
  addDrawToolbar(targetGroup = "Graficos",editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions()))%>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "sqmeters",
             activeColor = "#3D535D",
             completedColor = "#7D4479")%>% 
  addSearchGoogle() %>% 
  addControlGPS() %>% 
  addResetMapButton()

Mapa_2021= leaflet() %>%
  addControl(html = "<p><strong><em>Analisis de Desbosque- 2021</em></strong></p>",
             position = "topright")%>%
  addLogo(m,url = "https://images.vexels.com/media/users/3/143561/isolated/preview/afa3aa927b63061e3b0222b7dab9cdbf-ubicaci--n-n--utica-norte-flecha-vintage-by-vexels.png",
          position = "topleft",
          offset.x = 50,
          offset.y = 10,
          width = 100,
          height = 100)%>%
  addPolygons(data = Concesio, opacity = 0.6, group ="Concesion MARIZABETH",popup = polygon_popup) %>%
  addPolygons(data = Area_desbosb, opacity = 0.1, group ="Area Desboscada", color = "red" ,popup = polygon_popup3) %>%
  addCircles(data = Vertices ,popup = polygon_popup4,
             color = "red",
             radius =8,
             weight = 1,
             opacity = 1,
             fill = T,
             fillColor = "blue",
             fillOpacity = 1,
             group = "Vertices")%>%
  addRasterImage(Sent_2021 , project = TRUE,colors = pal, group = "Imagen Sentinel 2")%>%
  addLayersControl(baseGroups = c("Satellite", "OSM","OTM","Toner","Terrain","Terrain.ESRI", "Toner Lite","CartoDB.Positron", "relieve"),
                   overlayGroups = c("Imagen Sentinel 2", "Concesion MARIZABETH", "Vertices", "Area Desboscada"),
                   position = "topright",
                   options = layersControlOptions(collapsed = T))%>%
  addProviderTiles(providers$OpenStreetMap, group = "OSM")%>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite")%>%
  addProviderTiles(providers$OpenTopoMap, group = "OTM")%>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  addProviderTiles(providers$Esri.WorldStreetMap, group = "Terrain.ESRI") %>%
  addProviderTiles(providers$CartoDB.Positron, group ="CartoDB.Positron") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addMiniMap(tiles = providers$Esri.WorldImagery,toggleDisplay = TRUE)%>%
  addScaleBar(position = "bottomright",options = scaleBarOptions(maxWidth = 100,
                                                                 metric = TRUE,
                                                                 imperial = TRUE,
                                                                 updateWhenIdle = TRUE)) %>%
  addDrawToolbar(targetGroup = "Graficos",editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions()))%>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "sqmeters",
             activeColor = "#3D535D",
             completedColor = "#7D4479")%>% 
  addSearchGoogle() %>% 
  addControlGPS() %>% 
  addResetMapButton()
```


Informe Tecnico de Supervision
===========================================================================

Column 
---------------------------------------------------------------------------
### Mapa de Analisis de Desbosque para el 2016
```{r}
Mapa_2016
```



Column
---------------------------------------------------------------------------

### Mapa de Analisis de Desbosque para el 2021
```{r map}
Mapa_2021
```




